# Use an official Node.js image as the base image
FROM node:lts-slim

# Install necessary dependencies for Puppeteer and Chromium
RUN apt-get update && apt-get install -y \
  wget \
  ca-certificates \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdbus-1-3 \
  libgdk-pixbuf2.0-0 \
  libnspr4 \
  libnss3 \
  libx11-xcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  xdg-utils \
  libdrm2 \
  libgbm1 \
  libasound2-dev \
  libatk1.0-0 \
  libxss1 \
  libappindicator3-1 \
  libxtst6 \
  libnss3 \
  x11-utils \
  xvfb \
  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Install Puppeteer and dependencies
COPY package.json .
RUN npm install

# Copy the rest of the application files
COPY . .

# Run Xvfb and Puppeteer script
CMD Xvfb :99 -screen 0 1280x1024x24 & DISPLAY=:99 node kaisar.js